import type { Metadata } from "next";

import "../styles/global/globals.css";
import Header from "@/_components/Header/Header";
import Sidebar from "@/_components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <Sidebar />
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
